---
title: "Curriculum Vitae"
---
***

# <i class="fa fa-file"></i>   Conferences

2024  

2023  

2022  

Molecular Basis of Life, Düsseldorf  

__SFB960 Conference RNP Dynamics, Regensburg - selected talk__  

Microsymposium on RNA Biology, Vienna  

73rd Mosbacher Kolloquium, Mosbach  


2021 

EMBL PhD Symposium, online  

__13th GfE School - Stem cells, development, and regeneration, online - selected talk__  

AbGradE, online  

RED, online  


2020

__EMBO Sectoral meeting on RNA and Structural Biology, online, 2020 - Flash Talk__  

# <i class="fa fa-graduation-cap"></i>   Education 

2019-2024

PhD Molecular Medicine  
Hannover Biomedical Research School
Hannover Medical School

Hannover, Germany

2017-2019 

Biochemistry Master   
Life Sciences Center 
Vilnius University 

Vilnius, Lithuania

2018-2019 

M2 Biothérapies Tissulaires, Cellulaires, Géniques
Faculté de Médecine  
L'Université Paris-Est Créteil

Paris, France

2012-2017 

Biochemistry Bachelor  
Faculty of Chemistry, 
Vilnius University 

Vilnius, Lithuania

2012-2017 

IB Diploma,   
International Baccalaureate,  
Vilnius Lyceum, 

Vilnius, Lithuania

#  <i class="fa fa-flask"></i>   Research experience

2023-2024

Research Scholar, Mount Desert Island Biological Laboratory
Continuation of Rbfox1 research in Shcherbata laboratory.

2019-2023

PhD, Hannover Medical School, Institute of Cell Biochemistry  
Research project on Rbfox1 domains in Prof. Dr. Halyna Shcherbata's laboratory.

2016-2019

Internship, VU Institute of Biotechnology   
Recombinant protein production, DNA cloning with RE, E. coli transformation, optimization of growth conditions, protein purification using Ni-Chelating Sepharose column. Thermal shift assay, isothermal calorimetry titration, drug candidate research.

##  <i class="fa fa-briefcase"></i>   Work Experience

2017-2018 

Associate, Western Union   
Real Time Risk Assessment, customer service, global security and fraud prevention. 

# <i class="fa fa-cogs"></i>   Competences

* Biochemistry
* Molecular biology
* S2 cell culture
* Drosophila Genetics
* R Studio
* Basic LaTeX
* Teaching

# <i class="fa fa-language"></i>   Languages  

* English - very good
* Lithuanian - native
* French - moderate
* German - beginner

# <i class="fa fa-rocket"></i>   Interests  

* Science communication 
* Space, Exobiology
* Lindyhop, Salsa
* Choir singing 
* Bouldering
* Hiking
* Kayaking
* Science fiction